import streamlit as st
import matplotlib.pyplot as plt
import numpy as np
import json
import os

# Set page configuration
st.set_page_config(
    page_title="Privacy Mitigation Dashboard",
    page_icon="🚗",
    layout="wide"
)

# --- Load Data Dynamically ---
# The dashboard reads the JSON output generated by runner.py.
# This ensures that whenever you re-run the simulation, the dashboard updates automatically.
metrics_file = "results/metrics.json"

if os.path.exists(metrics_file):
    with open(metrics_file, "r") as f:
        metrics_data = json.load(f)
else:
    # Fallback to defaults if runner.py hasn't been executed
    metrics_data = {
        "Baseline": {"Tracking Success Rate (%)": 100.0, "Linkability (%)": 100.0},
        "Naive": {"Tracking Success Rate (%)": 99.2, "Linkability (%)": 98.8},
        "Smart": {"Tracking Success Rate (%)": 81.8, "Linkability (%)": 0.0},
        "Hybrid": {"Tracking Success Rate (%)": 40.0, "Linkability (%)": 0.0}
    }

# --- 1. Header & Introduction ---
st.title("🚗 Privacy Mitigation in Connected Vehicles: Performance Dashboard")

st.markdown("""
**The Problem:** Connected vehicles continuously broadcast Basic Safety Messages (BSMs) containing their location, speed, and heading.
Unauthorized entities can passively collect these broadcasts and link them over time using spatial-temporal heuristics.
By tracking these persistent identifiers, an attacker can reconstruct full vehicle routes, revealing travel patterns and profiling users.

This dashboard visualizes the effectiveness of various pseudonym-change mitigation strategies designed to break these tracking heuristics.
""")

st.divider()

# --- 2. The Strategy Comparison ---
st.header("The Strategies (Progressive Architecture)")

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.subheader("V1 - Baseline")
    st.markdown("""
    Vehicles use static identifiers for the duration of their trip. They continuously broadcast Basic Safety Messages (BSMs) with their real identities, making it trivial for an observer to track their full spatial-temporal path.
    """)
    st.code("""
# No Mitigations
vehicle.pseudonym = vehicle.original_id
# Broadcasts continuously
    """, language="python")

with col2:
    st.subheader("V2 - Naive Approach")
    st.markdown("""
    Vehicles blindly swap their pseudonyms at a fixed time interval (e.g., every 3 seconds), regardless of their surroundings.
    Because the vehicle is easily visible before and after the swap, the attacker can seamlessly link the new pseudonym to the old one based on trajectory continuation.
    """)
    st.code("""
# Naive Time-Based Swap
if current_time - last_swap_time >= 3:
    vehicle.pseudonym = generate_new_pseudonym()
    """, language="python")

with col3:
    st.subheader("V3 - Smart Mitigation")
    st.markdown("""
    Introduces a **Vehicle-Level Mix Zone**. A vehicle only changes its ID if it detects at least 2 other vehicles within a 50-meter radius.
    Once triggered, it undergoes a **Radio Silence Period**, stopping BSM broadcasts for a random 3 to 6 seconds while moving, thoroughly breaking the attacker's trajectory tracking.
    """)
    st.code("""
# Density + Random Silence
if nearby_vehicles >= 2:
    vehicle.pseudonym = generate_new_pseudonym()
    vehicle.silence_timer = random.randint(3, 6)
    """, language="python")

with col4:
    st.subheader("V4 - Hybrid Mitigation")
    st.markdown("""
    Introduces the **Cooperative Handshake** and **Adaptive Silence**. If a vehicle meets the density threshold, it checks if any neighbors also need a swap. They then perform the pseudonym swap simultaneously at the exact same simulation step.
    Additionally, the silence duration dynamically adjusts to physics: faster vehicles stay silent for less time.
    """)
    st.code("""
# Cooperative Swap + Velocity-Adaptive Silence
for neighbor in cooperative_group:
    neighbor.pseudonym = generate_new_pseudonym()

    # Adaptive Silence
    silence = max(3.0, min(10.0, 100.0 / max(0.1, n_speed)))
    neighbor.silence_timer = silence
    """, language="python")

st.divider()

# --- Create Tabs for the Interface ---
tab1, tab2 = st.tabs(["Metrics Comparison", "Trajectory Analysis"])

with tab1:
    # --- 3. The Key Metrics ---
    st.header("Simulation Results")

    col_metric1, col_metric2, col_metric3, col_metric4 = st.columns(4)

    base_succ = metrics_data["Baseline"]["Tracking Success Rate (%)"]
    base_link = metrics_data["Baseline"]["Linkability (%)"]
    naive_succ = metrics_data["Naive"]["Tracking Success Rate (%)"]
    naive_link = metrics_data["Naive"]["Linkability (%)"]
    smart_succ = metrics_data["Smart"]["Tracking Success Rate (%)"]
    smart_link = metrics_data["Smart"]["Linkability (%)"]
    hybrid_succ = metrics_data["Hybrid"]["Tracking Success Rate (%)"]
    hybrid_link = metrics_data["Hybrid"]["Linkability (%)"]

    with col_metric1:
        st.markdown("### 🔴 Baseline")
        st.metric(label="Tracking Success Rate", value=f"{base_succ:.1f}%")
        st.metric(label="Linkability", value=f"{base_link:.1f}%")

    with col_metric2:
        st.markdown("### 🟠 Naive")
        st.metric(label="Tracking Success Rate", value=f"{naive_succ:.1f}%", delta=f"{naive_succ - base_succ:.1f}%", delta_color="inverse")
        st.metric(label="Linkability", value=f"{naive_link:.1f}%", delta=f"{naive_link - base_link:.1f}%", delta_color="inverse")

    with col_metric3:
        st.markdown("### 🟡 Smart Mitigation")
        st.metric(label="Tracking Success Rate", value=f"{smart_succ:.1f}%", delta=f"{smart_succ - naive_succ:.1f}%", delta_color="inverse")
        st.metric(label="Linkability", value=f"{smart_link:.1f}%", delta=f"{smart_link - naive_link:.1f}%", delta_color="inverse")

    with col_metric4:
        st.markdown("### 🟢 Hybrid Mitigation")
        st.metric(label="Tracking Success Rate", value=f"{hybrid_succ:.1f}%", delta=f"{hybrid_succ - smart_succ:.1f}%", delta_color="inverse")
        st.metric(label="Linkability", value=f"{hybrid_link:.1f}%", delta=f"{hybrid_link - smart_link:.1f}%", delta_color="inverse")

    # --- 4. Eye-Catching Visualizations ---
    st.subheader("Performance Comparison Chart")

    labels = ['Tracking Success Rate (%)', 'Linkability (%)']

    baseline_values = [base_succ, base_link]
    naive_values = [naive_succ, naive_link]
    smart_values = [smart_succ, smart_link]
    hybrid_values = [hybrid_succ, hybrid_link]

    x = np.arange(len(labels))
    width = 0.20 # Slimmer bars to fit 4 groups

    fig, ax = plt.subplots(figsize=(12, 6))
    rects1 = ax.bar(x - 1.5*width, baseline_values, width, label='Baseline (No Mitigations)', color='#ffb3e6', edgecolor='black')
    rects2 = ax.bar(x - 0.5*width, naive_values, width, label='Scenario 2: Naive Approach', color='#ff9999', edgecolor='black')
    rects3 = ax.bar(x + 0.5*width, smart_values, width, label='Scenario 3: Smart Mitigation', color='#66b3ff', edgecolor='black')
    rects4 = ax.bar(x + 1.5*width, hybrid_values, width, label='Scenario 4: Hybrid Mitigation', color='#99ff99', edgecolor='black')

    ax.set_ylabel('Percentage (%)')
    ax.set_title('Privacy Metrics Drop Across Scenarios', pad=20)
    ax.set_xticks(x)
    ax.set_xticklabels(labels)
    ax.set_ylim(0, 115)
    ax.legend()

    # Attach a text label above each bar
    def autolabel(rects):
        for rect in rects:
            height = rect.get_height()
            ax.annotate(f'{height:.1f}%',
                        xy=(rect.get_x() + rect.get_width() / 2, height),
                        xytext=(0, 3),  # 3 points vertical offset
                        textcoords="offset points",
                        ha='center', va='bottom', fontweight='bold', fontsize=9)

    autolabel(rects1)
    autolabel(rects2)
    autolabel(rects3)
    autolabel(rects4)

    plt.tight_layout()
    st.pyplot(fig)

    st.divider()

    # --- 5. Visualizing the Broken Trajectories (Blue vs Red Lines) ---
    st.header("Trajectory Analysis")
    st.markdown("The charts below plot a sample vehicle's **Ground Truth Path (Solid Blue)** against the **Attacker's Track (Dotted Red)**. Notice how the advanced mitigations completely break the red line!")

    traj_file = "results/trajectories.json"
    if os.path.exists(traj_file):
        with open(traj_file, "r") as f:
            trajectories = json.load(f)

        # Display the 4 scenarios in a 2x2 grid for immediate visual comparison
        plot_col1, plot_col2 = st.columns(2)
        plot_col3, plot_col4 = st.columns(2)
        columns_layout = {"Baseline": plot_col1, "Naive": plot_col2, "Smart": plot_col3, "Hybrid": plot_col4}

        for scenario_name, target_col in columns_layout.items():
            data = trajectories.get(scenario_name, {})
            gt_path = data.get("ground_truth", [])
            att_path = data.get("attacker_track", [])

            with target_col:
                if gt_path and att_path:
                    fig, ax = plt.subplots(figsize=(6, 5))

                    # Plot Ground Truth
                    gt_x = [p["x"] for p in gt_path]
                    gt_y = [p["y"] for p in gt_path]
                    ax.plot(gt_x, gt_y, color='blue', linewidth=3, alpha=0.6, label='Ground Truth')

                    # Plot Attacker Track
                    att_x = [p["x"] for p in att_path]
                    att_y = [p["y"] for p in att_path]
                    ax.plot(att_x, att_y, color='red', linewidth=2, linestyle='--', marker='o', markersize=3, label='Attacker Track')

                    ax.set_title(f"{scenario_name} Trajectory", pad=10)
                    ax.set_xlabel("X (m)")
                    ax.set_ylabel("Y (m)")
                    ax.grid(True, linestyle=':', alpha=0.6)
                    ax.legend()

                    st.pyplot(fig)
                else:
                    st.warning(f"No trajectory data for {scenario_name}.")
    else:
        st.warning("Trajectory data not found. Please run `python runner.py` to generate `results/trajectories.json`.")

    st.divider()

    # --- 6. Insightful Summary ---
    st.info(f"""
    **Engineering Insights**

    **Interpreting the Results:**
    1. **The Baseline & Naive Failures:** Without mitigation, or with blind swaps, an attacker can easily track almost {base_succ:.1f}% of a vehicle's trajectory and link its digital identities.
    2. **V3 (Smart Mitigation) - The Digital Victory:** By waiting for density and using random silence, we successfully broke the digital identity chain (**{smart_link:.1f}% Linkability**). However, because road networks constrain physical movement, the attacker could still physically estimate ~{smart_succ:.1f}% of the trajectory.
    3. **V4 (Hybrid Mitigation) - Attacking Physical Tracking:** By introducing the Cooperative Handshake and Velocity-Adaptive Silence, we force vehicles to swap and go silent as synchronized groups with dynamic durations. This further degraded the attacker's physical tracking success down to **~{hybrid_succ:.1f}%**.

    **The Takeaway:** While completely hiding physical movement on constrained roads is notoriously difficult without RSU infrastructure, the V4 Hybrid Mitigation proves that a purely decentralized, vehicle-to-vehicle algorithm can entirely defeat digital linking ({hybrid_link:.0f}%) while degrading physical tracking by nearly {base_succ - hybrid_succ:.1f}%, establishing a robust privacy shield for connected vehicles.
    """)

with tab2:
    st.header("Technical Notes")
    st.markdown("""
    - **Simulation Stack**: Python 3, TraCI API, SUMO Engine.
    - **Attacker Heuristic Algorithm**: `Distance <= Speed * 1.5 + 10.0`
    - **Bounding Box Optimization**: O(N) spatial hashing check utilized prior to Euclidean distance checks to allow real-time density calculations.

    ### How to run the local simulation engine:
    ```bash
    # Generate new random traffic and evaluate mitigations
    python runner.py

    # Run the interactive dashboard
    streamlit run dashboard.py
    ```
    """)
